import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { readContent } from './content.js';
import type { CliEnv } from './env.js';
import { parseSource } from './frontmatter.js';
import { registry, type SkillEntry } from './registry.js';
import { descriptionOf } from './render.js';

/** The install targets `init` writes to, addressed by id. */
export type HarnessId = 'claude' | 'agents';

/** Every install target, in offer order. */
export const HARNESS_IDS: HarnessId[] = ['claude', 'agents'];

/** Whether an arbitrary string is one of the known install targets. */
export function isHarnessId(id: string): id is HarnessId {
  return (HARNESS_IDS as readonly string[]).includes(id);
}

/** Each harness's base directory, relative to the working directory; skills live under `<base>/skills`. */
export const HARNESS_BASE: Record<HarnessId, string> = {
  claude: '.claude',
  agents: '.agents',
};

/** The one stub is a skill named `wayfinder`; a harness serves it from this leaf. */
const STUB_SKILL = 'wayfinder';

const INDEX_START =
  '<!-- wayfinder:index:start — generated by `wayfinder init`. Do not edit; re-run `wayfinder init` to repair. -->';
const INDEX_END = '<!-- wayfinder:index:end -->';

/** The absolute path of the single stub file for one harness under the working directory. */
export function stubPath(env: CliEnv, harness: HarnessId): string {
  return join(env.cwd, HARNESS_BASE[harness], 'skills', STUB_SKILL, 'SKILL.md');
}

/** A harness is detected when its base directory already exists in the repo. */
export function detectHarnesses(env: CliEnv): HarnessId[] {
  return HARNESS_IDS.filter((id) => existsSync(join(env.cwd, HARNESS_BASE[id])));
}

/**
 * Whether a harness skill of this name is installed anywhere `doctor` looks: the
 * `claude` and `agents` targets, in project scope (under the working directory)
 * and user scope (under the home directory). A skill is a directory carrying a
 * `SKILL.md`, so that file's presence is the installed signal.
 */
export function harnessSkillInstalled(env: CliEnv, name: string): boolean {
  const roots = [env.cwd, env.home];
  for (const root of roots) {
    for (const id of HARNESS_IDS) {
      if (existsSync(join(root, HARNESS_BASE[id], 'skills', name, 'SKILL.md'))) return true;
    }
  }
  return false;
}

/**
 * Build the one stub skill `init` installs into a harness.
 *
 * The stub is agent-optimized: a hardened start line that leaves one legal next
 * move, plus a generated command map of the served skills only. It carries no
 * render-pipeline, tracker, or registration material — that content is for the
 * developer, not the agent. The command map regenerates from the registry, so
 * the served set stays the single source of truth and `init` is its only writer.
 */
export function buildStub(): string {
  const wayfinder = parseSource(readContent('skills/wayfinder/SKILL.md')).frontmatter;
  const rows = registry.filter(isMappedSkill).map(commandRow);
  return [
    '---',
    'name: wayfinder',
    `description: ${wayfinder.description ?? ''}`,
    'disable-model-invocation: true',
    '---',
    '',
    'Your next action MUST be to run `wayfinder skill wayfinder` (a Bash call) and follow its output. Do not act from this stub alone.',
    '',
    INDEX_START,
    'This project also serves — fetch each with `wayfinder skill <id>`:',
    '',
    ...rows,
    '',
    'Full index: `wayfinder skills`',
    INDEX_END,
    '',
  ].join('\n');
}

/**
 * The command map lists the served planning skills, so the map excludes the
 * `wayfinder` entry the start line already points at, and the `tracker` entry,
 * whose render is config-audience material that the stub deliberately omits.
 */
function isMappedSkill(entry: SkillEntry): boolean {
  return entry.origin === 'core' && entry.id !== 'wayfinder';
}

/** One command-map row: the served id, its description, and its disclosed children if any. */
function commandRow(entry: SkillEntry): string {
  const children = entry.children.map(leaf).join(', ');
  const note = children ? ` (children: ${children})` : '';
  return `- \`${entry.id}\` — ${descriptionOf(entry)}${note}`;
}

/** The leaf segment of a child id: `domain-modeling/adr-format` → `adr-format`. */
function leaf(id: string): string {
  return id.slice(id.lastIndexOf('/') + 1);
}

/**
 * A line-level diff between the stub on disk and the freshly built stub, as `- `
 * and `+ ` rows. `init` reports it when it repairs a damaged stub, so a second
 * run says exactly what it changed rather than failing or writing silently. The
 * walk is a standard longest-common-subsequence, so unchanged lines drop out and
 * only the real edits show.
 */
export function lineDiff(before: string, after: string): string[] {
  const a = before.split('\n');
  const b = after.split('\n');
  const lcs = lcsLengths(a, b);
  const commonFrom = (i: number, j: number): number => lcs[i]?.[j] ?? 0;

  const out: string[] = [];
  let i = 0;
  let j = 0;
  while (i < a.length && j < b.length) {
    if (a[i] === b[j]) {
      i += 1;
      j += 1;
    } else if (commonFrom(i + 1, j) >= commonFrom(i, j + 1)) {
      out.push(`- ${a[i]}`);
      i += 1;
    } else {
      out.push(`+ ${b[j]}`);
      j += 1;
    }
  }
  while (i < a.length) {
    out.push(`- ${a[i]}`);
    i += 1;
  }
  while (j < b.length) {
    out.push(`+ ${b[j]}`);
    j += 1;
  }
  return out;
}

/**
 * The longest-common-subsequence length table, filled from the bottom-right.
 * `commonFrom` reads past the last row and column on purpose — the base case of
 * the recurrence is zero — so the walk needs no separate bounds arithmetic.
 */
function lcsLengths(a: string[], b: string[]): number[][] {
  const table = Array.from({ length: a.length + 1 }, () => new Array<number>(b.length + 1).fill(0));
  const commonFrom = (i: number, j: number): number => table[i]?.[j] ?? 0;
  for (let i = a.length - 1; i >= 0; i -= 1) {
    const row = table[i];
    if (row === undefined) continue;
    for (let j = b.length - 1; j >= 0; j -= 1) {
      row[j] =
        a[i] === b[j]
          ? commonFrom(i + 1, j + 1) + 1
          : Math.max(commonFrom(i + 1, j), commonFrom(i, j + 1));
    }
  }
  return table;
}
